[workspace]
channels = ["conda-forge"]
name = "raman_wdf_simple_mapping"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
start = "python main.py"

[dependencies]
python = "3.12.*"
numpy = ">=2.3.4,<3"
plotly = ">=6.4.0,<7"
scipy = ">=1.16.3,<2"
